### ISSUE TITLE
eslint相关依赖没有自动安装

### ISSUE THREAD

**Issue by xiefei89** [gem-mine/gem-mine#1]
项目生成后，`package.json`中没有`eslint`相关依赖包

**Comment by caolvchong** [comment]
已支持 babel-eslint，plugins: ["react"], extends: ["standard", "standard-react"] 方式

已经使用脚手架构建的项目，可以按以下操作进行：
1. 对项目的代码纳入git（git add & commit），以防万一
2. 更新脚手架工具到最新（目前 0.1.7）：npm i gem-mine -g
3. 进行更新工程，在工程的父目录执行：gem-mine project_name，选择覆盖方式，其他选项按以前选择方式

更新完毕后，可以进入工程执行：npm run lint

可能遇到错误：TypeError: Cannot read property 'range' of null ...
参看： https://github.com/babel/babel-eslint/issues/530

临时解决方案：删除 node_modules、package-lock.json，然后重新执行 npm i
