### ISSUE TITLE
css中引用图片打包路径不正确

### ISSUE THREAD

**Issue by jerrylib** [gem-mine/gem-mine#3]
main.css 与 bg.png同属于同一路径层级打包生成的压缩文件带着相对路径“./bundle”。
版本：IE8兼容版
![default](https://user-images.githubusercontent.com/12061549/37581684-98337bd8-2b84-11e8-8677-a785573ad459.png)

**Comment by caolvchong** [comment]
已经处理，使用 gem-mine update 处理
参考文档：http://gem-mine.club/#/docs/api  或者 https://github.com/gem-mine/gem-mine/issues/6
